[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
anyhow = "1"
assert_matches = "1"
base64 = "0.22.1"
codex-code-mode = { path = "crates/code-mode" }
codex-code-mode-protocol = { path = "crates/code-mode-protocol" }
deno_core_icudata = "0.77.0"
dirs = "6"
dunce = "1"
futures = { version = "0.3", default-features = false }
pretty_assertions = "1"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
similar = "2"
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ["fs", "macros", "rt", "rt-multi-thread", "sync"] }
tokio-util = "0.7.18"
tracing = "0.1.44"
tree-sitter = "0.25"
tree-sitter-bash = "0.25.1"
url = "2"
urlencoding = "2"
v8 = "=149.2.0"
