import { configureTuiAppearance } from "pi-libtui";
import { createSettings } from "../sdk.ts";

export const tuiSettings = createSettings({
	namespace: "pi-libtui",
	label: "TUI",
	definitions: {
		iconPack: {
			category: "appearance",
			section: "Style",
			label: "Icon pack",
			description: "Icon set used by shared TUI components.",
			type: "enum",
			default: "unicode",
			options: [
				{ value: "nerd-fonts", label: "Nerd Fonts", description: "Patched-font icons." },
				{ value: "unicode", label: "Unicode", description: "Plain text Unicode symbols." },
				{ value: "emoji", label: "Emoji", description: "Color emoji symbols." },
			],
		},
		activityMarker: {
			category: "appearance",
			page: "animations",
			section: "General",
			preview: "activity-marker",
			label: "Activity marker",
			description: "Compact one-to-four-cell marker shown beside active work.",
			type: "enum",
			default: "spinner",
			options: [
				{ value: "off", label: "Off", description: "Do not show an activity marker." },
				{ value: "spinner", label: "Spinner", description: "Rotate a compact Braille spinner." },
				{ value: "pulse", label: "Pulse", description: "Pulse a fixed activity dot." },
				{ value: "static", label: "Static", description: "Show a fixed activity dot." },
				{ value: "line", label: "Line", description: "Rotate a compact ASCII line." },
				{ value: "arc", label: "Arc", description: "Rotate through rounded Unicode arc positions." },
				{ value: "pipe", label: "Pipe", description: "Rotate through box-drawing junctions." },
				{ value: "grow-vertical", label: "Vertical grow", description: "Grow and contract a vertical block." },
				{ value: "grow-horizontal", label: "Horizontal grow", description: "Grow and contract a horizontal block." },
				{ value: "triangle", label: "Triangle", description: "Rotate through filled triangle corners." },
				{ value: "circle-quarters", label: "Circle quarters", description: "Rotate a filled quarter around a circle." },
				{ value: "circle-halves", label: "Circle halves", description: "Rotate a filled half around a circle." },
				{ value: "bracket-spin", label: "Bracket spin", description: "Rotate an open bracket through four sides." },
				{ value: "dots", label: "Dots", description: "Move one Braille dot around its cell." },
				{ value: "quadrants", label: "Quadrants", description: "Move through the corners of one block cell." },
				{ value: "sparkle", label: "Sparkle", description: "Alternate a slow Unicode sparkle." },
				{ value: "braille-wave", label: "Braille wave", description: "Send a Braille dot wave across four cells." },
				{ value: "braille-dna", label: "Braille DNA", description: "Twist a Braille strand across four cells." },
				{ value: "braille-scan", label: "Braille scan", description: "Sweep a Braille bar across four cells." },
				{ value: "braille-rain", label: "Braille rain", description: "Drift a Braille rain pattern across four cells." },
				{ value: "braille-scanline", label: "Braille scanline", description: "Move a Braille scanline through three cells." },
				{ value: "braille-pulse", label: "Braille pulse", description: "Expand a Braille pulse across three cells." },
				{ value: "braille-sparkle", label: "Braille sparkle", description: "Scatter Braille sparks across four cells." },
				{ value: "braille-cascade", label: "Braille cascade", description: "Cascade a Braille wave across four cells." },
				{ value: "braille-columns", label: "Braille columns", description: "Fill three Braille columns in sequence." },
				{ value: "braille-orbit", label: "Braille orbit", description: "Orbit dots inside one Braille cell." },
				{ value: "braille-breathe", label: "Braille breathe", description: "Fill and empty one Braille cell." },
				{ value: "braille-wave-rows", label: "Braille wave rows", description: "Roll Braille rows across four cells." },
				{
					value: "braille-checkerboard",
					label: "Braille checkerboard",
					description: "Shift a three-cell Braille checkerboard.",
				},
				{ value: "braille-helix", label: "Braille helix", description: "Rotate a four-cell Braille double helix." },
				{ value: "scanline", label: "Scanline", description: "Fill and clear a three-cell Braille scanline." },
				{ value: "snake", label: "Snake", description: "Run a two-cell Braille snake around its track." },
				{ value: "fill-sweep", label: "Fill sweep", description: "Fill and clear two Braille cells vertically." },
				{
					value: "diagonal-swipe",
					label: "Diagonal swipe",
					description: "Sweep a diagonal fill through two Braille cells.",
				},
				{ value: "dna", label: "DNA", description: "Twist a compact three-cell Braille helix." },
				{ value: "radar", label: "Radar", description: "Sweep a Braille return across three cells." },
				{ value: "bounce", label: "Bounce", description: "Bounce a sparkle across three cells." },
				{ value: "orbit", label: "Orbit", description: "Orbit an arc around a compact sparkle." },
				{ value: "conveyor", label: "Conveyor", description: "Move a block along a three-cell track." },
				{ value: "heartbeat", label: "Heartbeat", description: "Pulse a compact ASCII heartbeat." },
				{
					value: "nerd-progress",
					label: "Progress spinner (Nerd Font)",
					description: "Rotate through the Fira Code progress-spinner glyphs.",
				},
				{ value: "nerd-morph", label: "Icon morph (Nerd Font)", description: "Morph through developer icons." },
				{
					value: "nerd-pipeline",
					label: "Pipeline (Nerd Font)",
					description: "Move build icons through a compact pipeline.",
				},
				{ value: "nerd-pi-orbit", label: "Pi orbit (Nerd Font)", description: "Orbit a spark around the Pi logo." },
			],
		},
		shimmer: {
			category: "appearance",
			page: "animations",
			section: "General",
			preview: "text-shimmer",
			label: "Text shimmer",
			description: "Highlight motion painted across active text.",
			type: "enum",
			default: "off",
			options: [
				{ value: "off", label: "Off", description: "Keep activity text steady." },
				{ value: "sweep", label: "Sweep", description: "Move a narrow highlight across activity text." },
				{ value: "glow", label: "Glow", description: "Move a broader multi-step glow across activity text." },
				{ value: "rainbow", label: "Rainbow", description: "Move a semantic color wave across activity text." },
			],
		},
		powerline: {
			category: "appearance",
			section: "Style",
			label: "Powerline separators",
			description: "Use rounded Powerline separators where supported.",
			type: "boolean",
			default: false,
		},
		powerlineButtons: {
			category: "appearance",
			section: "Style",
			label: "Powerline buttons",
			description: "Use rounded Powerline caps for buttons.",
			type: "boolean",
			default: false,
		},
		softCursor: {
			category: "appearance",
			section: "Style",
			label: "Softer virtual cursor",
			description: "Use a muted surface for virtual editor cursors.",
			type: "boolean",
			default: false,
		},
		insertionCursor: {
			category: "appearance",
			page: "terminal",
			section: "Cursor",
			label: "Insertion cursor",
			description: "Cursor used while editing text.",
			type: "enum",
			default: "virtual",
			options: cursorOptions(),
		},
		navigationCursor: {
			category: "appearance",
			page: "terminal",
			section: "Cursor",
			label: "Navigation cursor",
			description: "Cursor used while navigating without a selection.",
			type: "enum",
			default: "virtual",
			options: cursorOptions(),
		},
		selectionCursor: {
			category: "appearance",
			page: "terminal",
			section: "Cursor",
			label: "Selection cursor",
			description: "Cursor used at the active end of a selection.",
			type: "enum",
			default: "virtual",
			options: cursorOptions(),
		},
	},
});

function cursorOptions() {
	return [
		{ value: "virtual", label: "Virtual", description: "Paint the cursor into the TUI." },
		{ value: "terminal-default", label: "Terminal default", description: "Use the terminal's default cursor." },
		{ value: "blinking-block", label: "Blinking block", description: "Use a blinking block cursor." },
		{ value: "steady-block", label: "Steady block", description: "Use a steady block cursor." },
		{ value: "blinking-underline", label: "Blinking underline", description: "Use a blinking underline cursor." },
		{ value: "steady-underline", label: "Steady underline", description: "Use a steady underline cursor." },
		{ value: "blinking-bar", label: "Blinking bar", description: "Use a blinking bar cursor." },
		{ value: "steady-bar", label: "Steady bar", description: "Use a steady bar cursor." },
	] as const;
}

export function registerTuiSettings(): () => void {
	return tuiSettings.register((settings) => configureTuiAppearance(settings));
}
