import { configureTuiAppearance, TUI_ACTIVITY_MARKER_OPTIONS } from "pi-libtui";
import { createSettings } from "../sdk.ts";

export const tuiSettings = createSettings({
	namespace: "pi-libtui",
	label: "TUI",
	definitions: {
		iconPack: {
			category: "appearance",
			section: "Style",
			label: "Icon pack",
			description: "Icon set used by shared TUI components.",
			type: "enum",
			default: "unicode",
			options: [
				{ value: "nerd-fonts", label: "Nerd Fonts", description: "Patched-font icons." },
				{ value: "unicode", label: "Unicode", description: "Plain text Unicode symbols." },
				{ value: "emoji", label: "Emoji", description: "Color emoji symbols." },
			],
		},
		activityMarker: {
			category: "appearance",
			page: "animations",
			section: "General",
			preview: "activity-marker",
			label: "Activity marker",
			description: "Compact one-to-four-cell marker shown beside active work.",
			type: "enum",
			default: "spinner",
			options: TUI_ACTIVITY_MARKER_OPTIONS,
		},
		shimmer: {
			category: "appearance",
			page: "animations",
			section: "General",
			preview: "text-shimmer",
			label: "Text shimmer",
			description: "Highlight motion painted across active text.",
			type: "enum",
			default: "off",
			options: [
				{ value: "off", label: "Off", description: "Keep activity text steady." },
				{ value: "sweep", label: "Sweep", description: "Move a narrow highlight across activity text." },
				{ value: "glow", label: "Glow", description: "Move a broader multi-step glow across activity text." },
				{ value: "rainbow", label: "Rainbow", description: "Move a semantic color wave across activity text." },
				{
					value: "rainbow-glow",
					label: "Rainbow glow",
					description: "Move a broad rainbow glow and subdued color trail across activity text.",
				},
				{
					value: "lightning",
					label: "Lightning",
					description: "Move fast-mode strike and shine effects across activity text.",
				},
			],
		},
		shimmerMarker: {
			category: "appearance",
			page: "animations",
			section: "General",
			label: "Shimmer marker",
			description: "Apply the selected text shimmer to the activity marker too.",
			type: "boolean",
			default: false,
		},
		animationSpeed: {
			category: "appearance",
			page: "animations",
			section: "General",
			preview: "animation-speed",
			label: "Animation speed",
			description: "Pace of every activity marker and shimmer.",
			type: "enum",
			default: "normal",
			options: [
				{ value: "slow", label: "Slow", description: "Run animations at 60% of their normal pace." },
				{ value: "relaxed", label: "Relaxed", description: "Run animations at 80% of their normal pace." },
				{ value: "normal", label: "Normal", description: "Use each animation's designed pace." },
				{ value: "fast", label: "Fast", description: "Run animations at 135% of their normal pace." },
				{ value: "very-fast", label: "Very fast", description: "Run animations at 170% of their normal pace." },
			],
		},
		animationSmoothness: {
			category: "appearance",
			page: "animations",
			section: "General",
			preview: "animation-smoothness",
			label: "Animation smoothness",
			description: "Maximum repaint frequency used to preserve animation frames.",
			type: "enum",
			default: "balanced",
			options: [
				{ value: "economy", label: "Economy", description: "Use at most about 8 redraws per second." },
				{ value: "balanced", label: "Balanced", description: "Use at most about 17 redraws per second." },
				{ value: "smooth", label: "Smooth", description: "Use at most 25 redraws per second." },
				{ value: "ultra", label: "Ultra", description: "Use at most 40 redraws per second." },
			],
		},
		powerline: {
			category: "appearance",
			section: "Style",
			label: "Powerline separators",
			description: "Use rounded Powerline separators where supported.",
			type: "boolean",
			default: false,
		},
		powerlineButtons: {
			category: "appearance",
			section: "Style",
			label: "Powerline buttons",
			description: "Use rounded Powerline caps for buttons.",
			type: "boolean",
			default: false,
		},
		softCursor: {
			category: "appearance",
			section: "Style",
			label: "Softer virtual cursor",
			description: "Use a muted surface for virtual editor cursors.",
			type: "boolean",
			default: false,
		},
		insertionCursor: {
			category: "appearance",
			page: "terminal",
			section: "Cursor",
			label: "Insertion cursor",
			description: "Cursor used while editing text.",
			type: "enum",
			default: "virtual",
			options: cursorOptions(),
		},
		navigationCursor: {
			category: "appearance",
			page: "terminal",
			section: "Cursor",
			label: "Navigation cursor",
			description: "Cursor used while navigating without a selection.",
			type: "enum",
			default: "virtual",
			options: cursorOptions(),
		},
		selectionCursor: {
			category: "appearance",
			page: "terminal",
			section: "Cursor",
			label: "Selection cursor",
			description: "Cursor used at the active end of a selection.",
			type: "enum",
			default: "virtual",
			options: cursorOptions(),
		},
	},
});

function cursorOptions() {
	return [
		{ value: "virtual", label: "Virtual", description: "Paint the cursor into the TUI." },
		{ value: "terminal-default", label: "Terminal default", description: "Use the terminal's default cursor." },
		{ value: "blinking-block", label: "Blinking block", description: "Use a blinking block cursor." },
		{ value: "steady-block", label: "Steady block", description: "Use a steady block cursor." },
		{ value: "blinking-underline", label: "Blinking underline", description: "Use a blinking underline cursor." },
		{ value: "steady-underline", label: "Steady underline", description: "Use a steady underline cursor." },
		{ value: "blinking-bar", label: "Blinking bar", description: "Use a blinking bar cursor." },
		{ value: "steady-bar", label: "Steady bar", description: "Use a steady bar cursor." },
	] as const;
}

export function registerTuiSettings(): () => void {
	return tuiSettings.register((settings) => configureTuiAppearance(settings));
}
